### ISSUE TITLE
U200 compatibility

### ISSUE THREAD

**Issue by FredKellerman** [Xilinx/ACCL#145]
Hi,  thank you for this work!

The Alveo U200 is not listed as compatible.  Is it something that is possible but the team hasn't tested it or is there something that cannot be worked around with the U200?

**Comment by quetric** [comment]
Hi @FredKellerman 

U200 should work but we haven't tested on that platform since we don't have a board around. You would need to build your own config similar to the ones we have in test/hardware/config, for the specifics of the u200. I expect memory bank allocations and SLR constraints to be the only difference to the configs for other boards. 

Let me know if you need more help, and if you develop a config that works, please do a PR!
