### ISSUE TITLE
Harden DMA command segmentation

### ISSUE THREAD

**Issue by quetric** [Xilinx/ACCL#15]
A large part of the complexity of the firmware (and time spent in execution) is for managing the issuing and acknowledgement of DMA transfer segments. We should evaluate the feasibility and benefits of offloading the functionality to a HLS IP, which would reduce the firmware complexity and also improve latency especially for small messages.

**Comment by DanieleParravicini** [comment]
we offloaded dma_enqueue, dma_dequeue, dma_move_segmented
it's time to move also all operations that receive a segmented message and move them around.
It can be done :
1. by attaching to exchange_mem (easy and sound)
2. by attaching to dma_dequeue and extending dequeue to pass info about message received so that there's no need to read any memory

**Comment by quetric** [comment]
Closing, implemented in dev
