### ISSUE TITLE
Emulator parallelism limit

### ISSUE THREAD

**Issue by HPC-Ken** [Xilinx/ACCL#96]
Emulation with >8 threads is not supported. Request from 2 users

**Comment by quetric** [comment]
Fixed in cd1be8ec1e6f1

The problem was that openCon in the CCLO firmware issued all open connection requests to the TCP session handler before checking any of the responses. If the number of requests is larger than the request FIFO, it would stall. Fixed by issuing and checking one session at a time, so FIFO never fills.
